name: Build Mod
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          
      - name: Build
        # GamePath parametresini boş bir klasöre yönlendirerek sistemi kandırıyoruz
        run: |
          mkdir -p fake_game_folder
          dotnet build --configuration Release /p:GamePath="${{ github.workspace }}/fake_game_folder" /p:IgnoreModBuildConfigCheck=true
        
      - name: Pack
        run: |
          mkdir -p publish
          cp bin/Release/net6.0/MobileTouchEnhancer.dll publish/
          cp manifest.json publish/
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MobileTouchEnhancer-Package
          path: publish/
